# This file provides instructions for packaging.

`Types-Encodings`
	deps:runtime-requirement [ deps:on "perl 5.008001"^^deps:CpanId ];
	deps:runtime-requirement [ deps:on "Type::Library 0.004"^^deps:CpanId ];
	deps:test-requirement    [ deps:on "Test::More 0.96"^^deps:CpanId ];
	deps:test-requirement    [ deps:on "Test::TypeTiny"^^deps:CpanId ];
	.

